config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :songs
  root to: 'visitors#index'
  get 'about' => 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :users
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  validates :name, length: { in: 3..20}
  validates :tempo, numericality: { only_integer: true, :greater_than => 10, :less_than => 200}
  validates :vocals, :presence => true;

  default_scope {order('name ASC')}


end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :tempo, :vocals)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
= simple_form_for(@genre) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :tempo
    = f.input :vocals

  .form-actions
    = f.button :submit

app/views/genres/edit.html.haml
%h1 Editing genre

= render 'form' 

= link_to 'Show', @genre
\|
= link_to 'Back', genres_path
\|

%br
%br
= link_to 'Destroy', @genre, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/genres/index.html.haml
%h1.title Listing genres
.row
  .col-md-10.col-md-offset-1
    %table.table.table-condensed.table-striped
      %thead
        %tr
          %th Name
          %th Tempo
          %th Vocals
          %th Actions

      %tbody
        - @genres.each do |genre|
          %tr
            %td= genre.name
            %td= genre.tempo
            %td= genre.vocals 
            %td= link_to 'Edit', edit_genre_path(genre)

            %br

    = link_to 'New Genre', new_genre_path

.row
  .col-md-6.col-md-offset-3
    .transition1-title
      %h1 This is a transition
.row
  .transition1-container
    .col-md-2.col-md-offset-5
      .col-md-6.col-md-offset-3
        .transition1-box 
          %p stuff
.row
  .col-md-6.col-md-offset-3
    .transformation1-title
      %h1 This is a transformation
.row
  .transformation1-container
    .col-md-2.col-md-offset-5
      .col-md-6.col-md-offset-3
        .transformation1-box 
          %p stuff

app/views/genres/new.html.haml
%h1 New genre

= render 'form'

= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @genre.name
  %b Tempo:
  = @genre.tempo
  %b Vocals:
  = @genre.vocals

= link_to 'Edit', edit_genre_path(@genre)
\|
= link_to 'Back', genres_path