config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :songs
  root to: 'visitors#index'
  get 'about' => 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :full_name, :presence => true
  validates :email, :presence => true
  validates :city, :presence => true
  validates :country, :presence => true

  has_many :songs
  scope :admin, -> { where(admin: '1') }
  default_scope {order('full_name ASC')}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! , :only => :index
  before_action :check_user , :only => [:show , :edit , :update ]

  def index
    @q = User.search( params[:q] )
    @q.sorts = 'full_name asc' if @q.sorts.empty?
    @user_scope = @q.result(:distinct => true)
    @users = @user_scope.paginate( :page => params[:page], :per_page => 20 )
  end

  def check_user
    @user = User.where(:id => params[:id]).first
    @user = current_user unless @user
    current = current_user
    unless current == @user or current.admin
      return redirect_to :back, :alert => "Access denied."
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path , notice: 'Info successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        tag_given
      end
    end
  end

  def destroy
    unless current_user.admin
      return redirect_to :back, :alert => "Access denied."
    end
    @user = User.find(params[:id])
    @user.destroy
    if @user.destroy
        redirect_to users_url, notice: "User deleted."
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :info, :link,:city , :country , :state)
  end

end

app/views/users/_rules.html.haml
When you add a song, you get
access to the song database for
%b
  one month.
%br
%br
Each subsequent time you add a song you get a month of access.

app/views/users/_user.html.haml
%td= link_to user.full_name, user
%td= link_to user.email, user

app/views/users/edit.html.haml
.row
  .col-md-4
    -if admin?
      %h3
        Admin: Delete this user
      = link_to "Delete", admin_destroy_user_path(@user), method: :delete , class: "btn btn-danger",
              data: { confirm: "Can't undo this. Ok?" }
  .col-md-4.authform
    %h3
      Edit Info
    = simple_form_for(@user) do |f|
      .form-inputs
        = f.input :full_name
        = f.input :city
        = f.input :state , :label => "State/Province"
        = f.input :country , :as => :string
        = f.input :info
        = f.input :link , :label => "Link to your main dance (use full link, including http://, www., etc.)"

      .form-actions
        = f.button :submit

app/views/users/index.html.haml
.row
  .col-md-3
    %div
      %h1
        = @user_scope.length.to_s
        Users
  .col-md-9.m20
    = search_form_for @q, :html => { :class => "form-inline" }, :method => :get do |f|
      .form-group
        .input-group
          = f.text_field :full_name_cont , :class => "form-control" , :placeholder => "Name" , :size => 10
      .form-group
        .input-group
          = f.text_field :city_cont , :class => "form-control" , :placeholder => "City" , :size => 12
      .form-group
        .input-group
          = f.text_field :state_cont , :class => "form-control" , :placeholder => "State" , :size => 8
      .form-group
        .input-group
          = f.text_field :country_cont , :class => "form-control" , :placeholder => "Country" , :size => 12
      = f.submit "Search", :class => "btn btn-success" , :id => :filter
      = link_to  "Cancel", users_path, :class => "btn btn-warning"
.row
  .col-md-12
    %table.table.table-condensed.table-striped
      %thead
        %tr
          %th= sort_link @q , :name
          %th= sort_link @q , :city
          %th= sort_link @q , :state , "State/Province"
          %th= sort_link @q , :country
          -if admin?
            %th= sort_link @q , :given , "Latest Song Added"
            %th= sort_link @q , :used
            %th= sort_link @q , :count
          %th Link
          %th Info
      %tbody
        - @users.each do |user|
          %tr{:class => "line-#{cycle("1","2")}"}
            %td
              -if admin?
                = link_to user.full_name , user
              -else
                = user.full_name
            %td= user.city
            %td= user.state
            %td= user.country
            -if admin?
              %td= user.given
              %td= user.used
              %td= user.count
            %td
              = link_to( song_text(user) , user.link , :target => :_blank) if user.link

            %td
              = user.info
              = link_to( " (edit)" , edit_user_path(user))  if admin?
  = paginate @users

app/views/users/show.html.haml
%h3 User
%p
  Name:
  =@user.full_name.to_s
%p
  Email:
  = @user.email
%p
  Info:
  = @user.info
%p
  Added:
  = @user.added
%p
  City:
  = @user.city
%p
  State/Province:
  = @user.state
%p
  Country:
  = @user.country
%p
  Hear:
  = @user.hear
%p
  Group:
  = @user.group