config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :songs
  root to: 'visitors#index'
  get 'about' => 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :users
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, :presence => true
  validates :artist, :presence => true
  validates :album, :presence => true
  validates :tempo, :presence => true
  validates :main_genre_id, :presence => true

  default_scope {order('date_added DESC')}

  belongs_to :user
  belongs_to :main_genre ,  :class_name => 'Genre'

  def user_name
    if self.user_id and self.user
      self.user.full_name
    else
      self.read_attribute(:user_name)
    end
  end

  def added_on
    return self.date_added if self.date_added
    self.added
  end

  def self.tempo_list
     ["ambient", "very slow", "slow", "medium-slow", "medium", "medium-fast",
       "fast", "very fast", "varies"]
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , :only => [:index , :edit , :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @q = Song.ransack( params[:q] )
    @q.sorts = 'date_added desc' if @q.sorts.empty?
    @song_scope = @q.result(:distinct => true).includes(:user).includes(:main_genre)
    @songs = @song_scope.paginate( :page => params[:page], :per_page => 20 )
    tag_used
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @song.date_added = Date.today

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
        tag_given
        SongMailer.notify(@song).deliver_later
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to songs_path, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    unless current_user.admin
      return redirect_to :back, :alert => "Access denied."
    end
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def tag_used
      user = current_user
      user.used = Date.today
      user.count += 1
      user.save!
    end

    def tag_given
      user = current_user
      user.given = Date.today
      user.count = 0
      user.save!
    end

    def check_given
      current = current_user
      return unless current
      given = current.given
      if !given or ((Date.today - 1.month) > given )  # && ( current.count > 5 )
        return redirect_to :new_song, :alert => "Read below on the rules of this service."
      end
    end

    def check_user
      @song = Song.where(:id => params[:id]).first
      current = current_user
      return unless current
      unless current.id == @song.user_id or current.admin
        return redirect_to root_path , :alert => "Access denied."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit( :title, :artist, :album, :tempo, :main_genre_id,:sub_genre,
                                    :link, :info , :user_id, :"date_added(1i)",
                                    :"date_added(2i)", :"date_added(3i)")
    end
end

app/helpers/songs_helper.rb
module SongsHelper
  def tempo_label(song)
    label = "Tempo"
    return label if song.new_record?
    if Song.tempo_list.index(song.tempo).nil?
      label += " (was #{song.tempo})"
    end
    label
  end
end

app/views/songs/_form_fields.html.haml
.form-inputs
  = f.input :title
  = f.input :artist
  = f.input :album
  = f.input :tempo, collection: Song.tempo_list ,include_blank: false , :label => tempo_label(@song)
  = f.association :main_genre , :include_blank => false
  = f.input :sub_genre
  = f.input :link , :label => "Link (use full link to a sample of this song, including http://, www., etc.)"
  = f.input :info, :label => "Info (for example, is this an instrumental? Notable lyrics? Something unusual about the song? Is there a long intro or outro?"


.form-actions
  = f.button :submit

app/views/songs/edit.html.haml
.row
  .col-md-3
  .col-md-6
    %h1 Editing song

    = simple_form_for(@song) do |f|
      = f.error_notification

      .form-inputs
        %br
        = f.label "Song added by: #{@song.user_name}"
        = f.label "Song added at: #{@song.added_on}"
          -if admin?
          = f.input :date_added , :label => "Original date: #{@song.added}"
      = render 'form_fields' , { :f => f}
    %br
    -if admin?
      = link_to "Delete", song_path(@song), method: :delete , class: "btn btn-danger",
              data: { confirm: "Can't undo delete. Ok?" }
    \|
    = link_to 'Cancel', songs_path

app/views/songs/index.html.haml
.row
  .col-md-3
    %div
      %h1= @song_scope.length.to_s + " Songs"
  .col-md-9.m20
    = search_form_for @q, :html => { :class => "form-inline" }, :method => :get do |f|
      .form-group
        = f.text_field :user_name_or_user_full_name_cont , :class => "form-control" , :placeholder => "User" , :size => 10
      .form-group
        = f.text_field :title_cont , :class => "form-control" , :placeholder => "Title", :size => 10
      .form-group
        = f.text_field :artist_cont , :class => "form-control" , :placeholder => "Artist", :size => 10
      .form-group
        = f.collection_select :main_genre_name_or_sub_genre_cont, Genre.all, :name, :name, {include_blank: "Genre" }, :class => "form-control"
      .form-group
        = f.collection_select :tempo_cont, Song.tempo_list ,:to_s , :to_s,  {include_blank: "Tempo" }, :class => "form-control"
      = f.submit "Search", :class => "btn btn-success" , :id => :filter
      = link_to  "Cancel", songs_path, :class => "btn btn-warning"
.row
  .col-md-12
    %table.table.table-condensed.table-striped
      %thead
        %tr
          %th= sort_link @q , :date_added
          %th= sort_link @q , :user_name
          %th= sort_link @q , :title
          %th= sort_link @q , :artist
          %th= sort_link @q , :album
          %th= sort_link @q , :tempo
          %th= sort_link @q , :main_genre
          %th= sort_link @q , :sub_genre
          %th Link
          %th Info

      %tbody
        - @songs.each do |song|
          %tr{:class => "line-#{cycle("1","2")}"}
            %td.title= song.date_added.to_s
            %td.title= song.user_name
            %td.title= song.title
            %td.title= song.artist
            %td.title= song.album
            %td.title= song.tempo
            %td.title= song.main_genre.name if song.main_genre
            %td.title= song.sub_genre
            %td.title
              = link_to( song_text(song) , song.link , :target => :_blank) unless song.link.blank?
            %td.title
              = song.info
              -if (admin? or current_user.id == song.user_id)
                = link_to 'Edit', edit_song_path(song)

    = paginate @songs
  %br

app/views/songs/new.html.haml
.row
  .col-md-1
  .col-md-4
    %h1 Give to use

    = render "users/rules"
    %br
    %br
    		
    Please only suggest songs that don't promote prejudice, violence, substance abuse, hatred, or stereotypes, and that others can readily sample online and purchase

  .col-md-1
  .col-md-5
    %h1 Add a new song
    = simple_form_for(@song) do |f|
      = f.error_notification

      .form-inputs
        %br
        = f.hidden_field :user_id , :value => current_user.id
      = render 'form_fields' , { :f => f}

    = link_to 'Cancel', songs_path

app/views/songs/show.html.haml
%p#notice= notice

%p
  %b User:
  = @song.user_name
%p
  %b Added:
  = @song.date_added.to_s
%p
  %b Title:
  = @song.title
%p
  %b Artist:
  = @song.artist
%p
  %b Album:
  = @song.album
%p
  %b Speed:
  = @song.tempo
%p
  %b Main Genre:
  = @song.main_genre.name if @song.main_genre
%p
  %b Sub Genre:
  = @song.sub_genre
%p
  %b Link:
  = link_to( song_text(@song) , @song.link , :target => :_blank) unless @song.link.blank?
%p
  %b Info:
  = @song.info

= link_to 'Back to list', songs_path