config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resources :songs
  root to: 'visitors#index'
  get 'about' => 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :users
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top.navbar-text-alice
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li= link_to 'Songs', songs_path
          %li= link_to 'Users', users_path
          %li= link_to 'Add a song', new_song_path
          %li= link_to( 'Genres', genres_path) if admin?
        - else
          %li= link_to 'Login', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to 'About', about_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle"=>"dropdown","role"=>"button" ,
                  "aria-haspopup" => "true" , "aria-expanded" => "false" , "href" => "#" }
              Profile
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'Edit profile', edit_user_path(current_user)
              %li= link_to 'Edit account', edit_user_registration_path
              %li= link_to 'Logout', destroy_user_session_path, :method=>'delete'
      -else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to 'About', about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Deejays'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Deejays'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .row
        .col-md-1
        .col-md-10
          = render 'layouts/messages'
          = yield